### ISSUE TITLE
Looking forward to your code!

### ISSUE THREAD

**Issue by Yangjinluan** [draym28/LSGNN#1]
Hello! I am very interested in your research! And my research also focus on Heterogeneous graph learning. I would greatly appreciate it if you could release the code！ Thank you!

**Comment by Luo-Yihong** [comment]
Hi, thanks for your interest. 
To be honest, we are busy with other projects now, the code will be released as soon as possible.

And, btw, this work is related to heterophily :)

**Comment by SONGLEI-arch** [comment]
Hello, I am very interested in your work. Could you please provide the code for the model first ？
